### ISSUE TITLE
Calculix 2.21 available 

### ISSUE THREAD

**Issue by stefano2734** [calculix/new_keywords#1]
So a run for calculix 2.21 is possible with 141 keywords
http://www.dhondt.de/new_calc.htm
http://www.dhondt.de/cgx_2.21.pdf
http://www.dhondt.de/ccx_2.21.pdf

**Comment by imirzov** [comment]
Thank you! Would you help to create an updated keyword list?

**Comment by stefano2734** [comment]
an extraction from pdf is the workflow.
But I see here no script or workflow.

Keywords are at page 7 to 9 in ccx.pdf

I see the .py-file but no example source file for extraction.

**Comment by imirzov** [comment]
To create text files with keyword lists I used Ctrl-C, Ctrl-V and manual edition.

**Comment by stefano2734** [comment]
Ok in next days, I will show about it with libreoffice calc and an editor for fast extraction.
Grep will show differences and additions to previous.

**Comment by stefano2734** [comment]
CCX 221: 
6 new to 2.20
*CHANGE CONTACT TYPE
*INITIAL MESH
*MATRIX ASSEMBLE
*MOHR COULOMB 
*MOHR COULOMB HARDENING
*RATE DEPENDENT

*AMPLITUDE 
*BASE MOTION 
*BEAM SECTION 
*BOUNDARY 
*BUCKLE  
*CFD   
*CFLUX  
*CHANGE CONTACT TYPE                   (new)
*CHANGE FRICTION  
*CHANGE MATERIAL  
*CHANGE PLASTIC  
*CHANGE SOLID SECTION 
*CHANGE SURFACE BEHAVIOR 
*CLEARANCE  
*CLOAD  
*COMPLEX FREQUENCY  
*CONDUCTIVITY  
*CONSTRAINT  
*CONTACT DAMPING  
*CONTACT FILE  
*CONTACT OUTPUT  
*CONTACT PAIR  
*CONTACT PRINT  
*CONTROLS  
*CORRELATION LENGTH  
*COUPLED TEMPERATURE-DISPLACEMENT 
*COUPLING  
*CRACK PROPAGATION  
*CREEP  
*CYCLIC HARDENING  
*CYCLIC SYMMETRY MODEL 
*DAMPING  
*DASHPOT  
*DEFORMATION PLASTICITY 
*DENSITY  
*DEPVAR  
*DESIGN RESPONSE  
*DESIGN VARIABLES  
*DFLUX  
*DISTRIBUTING  
*DISTRIBUTING COUPLING 
*DISTRIBUTION  
*DLOAD  
*DSLOAD  
*DYNAMIC  
*ELASTIC  
*ELECTRICAL CONDUCTIVITY 
*ELECTROMAGNETICS  
*ELEMENT  
*ELEMENT OUTPUT  
*EL FILE  
*EL PRINT  
*ELSET  
*END STEP  
*EQUATION  
*EXPANSION  
*FEASIBLE DIRECTION  
*FILM  
*FILTER  
*FLUID CONSTANTS  
*FLUID SECTION  
*FREQUENCY  
*FRICTION  
*GAP   
*GAP CONDUCTANCE  
*GAP HEAT GENERATION  
*GEOMETRIC CONSTRAINT 
*GEOMETRIC TOLERANCES 
*GREEN  
*HCF   
*HEADING  
*HEAT TRANSFER  
*HYPERELASTIC  
*HYPERFOAM  
*INCLUDE  
*INITIAL CONDITIONS  
*INITIAL MESH                          (new)
*INITIAL STRAIN INCREASE 
*KINEMATIC  
*MAGNETIC PERMEABILITY 
*MASS  
*MASS FLOW  
*MATERIAL  
*MATRIX ASSEMBLE                       (new)
*MEMBRANE SECTION  
*MODAL DAMPING  
*MODAL DYNAMIC  
*MODEL CHANGE  
*MOHR COULOMB                          (new)
*MOHR COULOMB HARDENING                (new)
*MPC   
*NETWORK MPC  
*NO ANALYSIS  
*NODAL THICKNESS  
*NODE  
*NODE FILE  
*NODE OUTPUT  
*NODE PRINT  
*NORMAL  
*NSET  
*OBJECTIVE  
*ORIENTATION  
*OUTPUT  
*PHYSICAL CONSTANTS  
*PLASTIC  
*PRE-TENSION SECTION  
*RADIATE  
*RATE DEPENDENT                        (new)
*REFINE MESH  
*RESTART  
*RETAINED NODAL DOFS  
*RIGID BODY  
*ROBUST DESIGN  
*SECTION PRINT  
*SELECT CYCLIC SYMMETRY MODES 
*SENSITIVITY  
*SHELL SECTION  
*SOLID SECTION  
*SPECIFIC GAS CONSTANT 
*SPECIFIC HEAT  
*SPRING  
*STATIC  
*STEADY STATE DYNAMICS 
*STEP  
*SUBMODEL  
*SUBSTRUCTURE GENERATE 
*SUBSTRUCTURE MATRIX OUTPUT 
*SURFACE  
*SURFACE BEHAVIOR  
*SURFACE INTERACTION  
*TEMPERATURE  
*TIE   
*TIME POINTS  
*TRANSFORM  
*UNCOUPLED TEMPERATURE-DISPLACEMENT 
*USER ELEMENT  
*USER MATERIAL  
*USER SECTION  
*VALUES AT INFINITY  
*VIEWFACTOR  
*VISCO

**Comment by imirzov** [comment]
Thanks for the contribution. I've updated the main [README.md file](https://github.com/calculix/new_keywords?tab=readme-ov-file#CALCULIX).
