### ISSUE TITLE
Abaqus 2023 available with perhaps new keywords

### ISSUE THREAD

**Issue by stefano2734** [calculix/new_keywords#2]
https://www.4realsim.com/abaqus-2023-release-available/

Version 2024 is available too.
https://optimec.ca/blog/abaqus-2024-whats-new/

**Comment by imirzov** [comment]
Thank you! Would you help to create an updated keyword list?

**Comment by stefano2734** [comment]
Abaqus manual 2023 and 2024 is not available for me. 
Script and workflow to extract from pdfof this project? Where is it?
or was it made by hand?

**Comment by imirzov** [comment]
Everything was made by hand. Right now I also have no access to new Abaqus versions. So, let's leave it as is for better times.

**Comment by imirzov** [comment]
Solved here:
https://github.com/calculix/new_keywords/commit/eb6aa4c8f5ed896cc3b48dcf8b04f2b811cba530
